version: "3.5"
services:
  docker-web:
    # replace username/repo:tag with your name and image details
    image: syngine/docker-web:latest
    build:
      context: ./docker-web
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    # deploy:
    #   replicas: 5
      # resources:
      #   limits:
      #     cpus: "0.1"
      #     memory: 50M
      # restart_policy:
      #   condition: on-failure
    networks:
      - webnet
  
  docker-nginx:
    image: syngine/docker-nginx:latest
    build:
      context: ./docker-nginx
      dockerfile: ./Dockerfile
    ports:
      - "5000:8800"
    networks:
      - webnet

networks:
  webnet: